# Generated by Django 4.1.2 on 2022-10-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StudentID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('BatchNo', models.CharField(max_length=15)),
                ('ContactNo', models.CharField(max_length=15)),
                ('ContactAddress', models.CharField(max_length=100)),
                ('EmailAddress', models.EmailField(max_length=254)),
            ],
        ),
    ]
