# Generated by Django 4.1.2 on 2022-11-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App01', '0003_trainee_dueamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='DueAmount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
