# Generated by Django 4.1.2 on 2022-11-03 14:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App01', '0007_alter_trainee_dueamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='DueAmount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
    ]
